### ISSUE TITLE
GIS fields for all component types

### ISSUE THREAD

**Issue by akbarnes** [sanderclaeys/pmd-data-model#29]
I don't think that this is in the writeup, but I did notice that buses in the engineering model have lat/lons associated with them, but other components don't. Consider adding support for geojson geometry objects to both edge and node type objects, with particular emphasis on supporting linestrings for lines, a shortcoming of most tools.

**Comment by pseudocubic** [comment]
Actually, I don't think we standardized around any GIS information in the eng model, because PowerModelsDistribution is not location-aware, so it felt out of scope. Rather, since the model is extensible, in that it is a simple dictionary structure which is serializable into JSON, any additions to the model by Users that do not collide with the specified data fields can be supported without issue.

In the parsing of OpenDSS files we do support the use of buscoords files, which are lat/lons, given in units of decimal degrees, and we will parse those by default into the data structure.

If we do want to specify supported GIS fields in the engineering model, I think that should be opened for discussion in the PowerModelsDistribution repository after this model goes live. I might suggest however that supported GIS fields might be specified in PowerModelsAnalytics instead, since that is our only plotting package, but we should definitely have that discussion.

**Comment by ccoffrin** [comment]
This feature has come up a sufficient number of times I would like to have a standard approach for all of InfrastructureModels packages.  I agree with @pseudocubic that it seems orthogonal in scope for the near term goals of this data model and can be revisited once the basic eng data model is working.
