### ISSUE TITLE
Voltage Zone Motivations

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#47]
I am not sure why these are included.  If they are just a "helper" for setting bounds I would remove them.  If they serve additional purpose I would keep them with that extra explanation.

**Comment by sanderclaeys** [comment]
@frederikgeth I seem to remember you were a fan of these

**Comment by ccoffrin** [comment]
Maybe helpful in doing the per-unit calculaiton?

**Comment by pseudocubic** [comment]
right now we calculate the voltage zones automatically in order to do the conversion to per-unit, but it we have a `voltage_zone` object we can skip this step and go straight to the pu conversion. I could imagine that our algorithm to detect the zones could create these objects and then the user could edit the values to debug optimization?

**Comment by pseudocubic** [comment]
component is not being active used in the current refactor and implementation would not be a breaking change, pushing discussion to PMD repo
