### ISSUE TITLE
Time Series Multiply vs Replace

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#48]
I am not sure there is a lot of added value from multiply over replace, replace is more general.  Is there some motivation for also supporting multiply?

**Comment by pseudocubic** [comment]
Actually, multiply is the more common case, because you might have one common loadshape for a large collection of loads, which will each have its own base load value. If we only do replace at the engineering level, we would need to generate time series for each individual load instead of only having one. Then there’s the one case where multiply won’t work, if the starting base load is zero.

**Comment by ccoffrin** [comment]
The example you mention is fairly common, but I am not sure it is reflective of real data.  It is a common hack that one uses to turn a data snap-shot into a multi-period dataset.  I generally would not advocate for this as it encourages sloppy modeling.

On use case that _might_ be reasonable for multiply is the amount of sun hitting a bunch of nearby solar panels, they are correlated in space so one source of data for the base amount of sun would be consistent.

**Comment by pseudocubic** [comment]
We will continue to support both multiply and replace at the engineering level, but follow any existing multinetwork conventions at the mathematical level
