### ISSUE TITLE
Consistency of Component Specialization 

### ISSUE THREAD

**Issue by ccoffrin** [sanderclaeys/pmd-data-model#54]
In the case of loads there is a parameter called "model" in the case of shunts there are new components, "shunt_capacitor" and "shunt_reactor".  You might consider if a consistent convention can be defined when a patermeter like "model" should be used and when a new component type should be used.

**Comment by pseudocubic** [comment]
the only advantage i really see to having shunt_capacitor, shunt_reactor, and shunt is to prevent name collision between different shunt like objects that we get from opendss. 

Capacitors and reactors could both have an object named e.g. "this_is_a_shunt", and they won't collide in opendss, but if we put them all under `shunt` in PMD we need to rename the colliding id, or else fail out of the parse with an error message explaining why.

I'm hesitant to rename a particular component id, because it makes it harder to find, but maybe we convert the names to be their source ids instead if we want to combine them? On the other hand, failing out of the parse feels a little user unfriendly.

The other alternative is to split out loads into different components, but what do we name them? `power_load`, `current_load`, `impedance_load`, `exponential_load`, and `zip_load` sound more natural than the reverse, but the reverse follows our naming conventions better.

Honestly, a solution that combines everything under `shunt` feels less cluttered to me, and would be my preference if we can settle on a consistent way to handle name collisions.

**Comment by pseudocubic** [comment]
proposal is to collapse objects into `shunt`, with `model` parameter to provide engineering details (see #42), but to throw a warning at name collision and prepend name with originating component. E.g. if there is a capacitor named `shunt` already parsed into the `shunt` components, and a reactor named `shunt` needs to be parsed in, we will rename to `reactor.shunt` and throw a warning informing the user of the name change
